package com.g2forge.gearbox.command.nested;

import java.util.List;
import java.util.stream.Collectors;

import com.g2forge.alexandria.command.invocation.CommandInvocation;
import com.g2forge.alexandria.command.invocation.CommandInvocation.CommandInvocationBuilder;
import com.g2forge.alexandria.java.core.error.UnreachableCodeError;
import com.g2forge.alexandria.java.function.IConsumer1;
import com.g2forge.alexandria.java.function.IFunction1;
import com.g2forge.gearbox.command.converter.dumb.DumbCommandConverter;
import com.g2forge.gearbox.command.process.redirect.IRedirect;
import com.g2forge.gearbox.command.proxy.CommandProxyFactory;
import com.g2forge.gearbox.command.proxy.ICommandProxyFactory;
import com.g2forge.gearbox.command.proxy.process.ModifyProcessInvocationException;
import com.g2forge.gearbox.command.proxy.process.ProcessInvocation;
import com.g2forge.gearbox.command.proxy.process.ProcessInvocation.ProcessInvocationBuilder;
import com.g2forge.gearbox.command.proxy.process.ReturnProcessInvocationException;
import com.g2forge.gearbox.command.proxy.result.IResultSupplier;

public class HNestedCommand {
	public static final ICommandProxyFactory COMMAND_PROXY_FACTORY = new CommandProxyFactory(new DumbCommandConverter(), null);

	public static <T> ModifyProcessInvocationException modify(Class<T> type, IConsumer1<? super T> command) {
		return modify(type, command, null, null);
	}

	public static <T> ModifyProcessInvocationException modify(Class<T> type, IConsumer1<? super T> command, IArgumentModifier arguments) {
		return new ModifyProcessInvocationException(processInvocation -> {
			try {
				command.accept(COMMAND_PROXY_FACTORY.apply(type));
				// This line cannot be reached, as the COMMAND_PROXY_FACTORY will ALWAYS throw an exception due to the null runner.
				throw new UnreachableCodeError();
			} catch (final ReturnProcessInvocationException exception) {
				return modify(arguments, processInvocation, exception, false);
			}
		});
	}

	public static <T> ModifyProcessInvocationException modify(Class<T> type, IConsumer1<? super T> command, String join, IFunction1<? super String, ? extends String> wrap) {
		return modify(type, command, (commandInvocation, builder) -> {
			if (join != null) {
				final String joined = commandInvocation.getArguments().stream().collect(Collectors.joining(join));
				final String wrapped = (wrap == null) ? joined : wrap.apply(joined);
				builder.argument(wrapped);
			} else {
				final List<String> arguments = commandInvocation.getArguments();
				final List<String> wrapped = (wrap == null) ? arguments : (arguments.stream().map(wrap).collect(Collectors.toList()));
				builder.arguments(wrapped);
			}
		});
	}

	public static <T> ModifyProcessInvocationException modify(Class<T> type, IFunction1<? super T, ?> command, IArgumentModifier arguments) {
		return new ModifyProcessInvocationException(processInvocation -> {
			try {
				command.accept(COMMAND_PROXY_FACTORY.apply(type));
				// This line cannot be reached, as the COMMAND_PROXY_FACTORY will ALWAYS throw an exception due to the null runner.
				throw new UnreachableCodeError();
			} catch (final ReturnProcessInvocationException exception) {
				return modify(arguments, processInvocation, exception, true);
			}
		});
	}

	protected static ProcessInvocation<?> modify(IArgumentModifier arguments, ProcessInvocation<?> processInvocation, final ReturnProcessInvocationException exception, boolean modifyResultSupplier) {
		// Here we extract the command generated by the lambda, and pass it as additional arguments to the process invocation we're building
		final CommandInvocationBuilder<IRedirect, IRedirect> commandInvocationBuilder = processInvocation.getCommandInvocation().toBuilder();
		final CommandInvocation<IRedirect, IRedirect> commandInvocation = exception.getProcessInvocation().getCommandInvocation();
		arguments.accept(commandInvocation, commandInvocationBuilder);

		final ProcessInvocationBuilder<?> processInvocationBuilder = processInvocation.toBuilder();

		if (modifyResultSupplier) {
			// Use the nested result supplier for the outer command, and pass through the stdio redirect too
			@SuppressWarnings({ "rawtypes", "unused", "unchecked" })
			final ProcessInvocationBuilder temp = processInvocationBuilder.resultSupplier((IResultSupplier) exception.getProcessInvocation().getResultSupplier());
			commandInvocationBuilder.io(exception.getProcessInvocation().getResultSupplier().createRedirect());
		}

		// Override the actual command
		processInvocationBuilder.commandInvocation(commandInvocationBuilder.build());
		return processInvocationBuilder.build();
	}
}
